In [1]:
import random
from collections import Counter

In [4]:
def choice():
    t = Counter()
    for i in range(3):
        t[random.randint(1,2)] += 1

    if t[1] > t[2]: 
        print('选择 搜狗')
    else:
        print('选择头条')
for i in range(3):
    choice()
#     print()

选择 搜狗
选择头条
选择 搜狗


In [2]:
import numpy as np
import pandas as pd

In [3]:
l = np.arange(10)
np.random.shuffle(l)

In [21]:
np.random.choice(l,10,replace=False)

array([4, 1, 6, 8, 3, 0, 5, 7, 2, 9])

In [20]:
np.stack([np.arange(10),np.arange(10)])

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
s = pd.Series(l)

In [4]:
l

array([1, 6, 8, 4, 9, 7, 0, 2, 3, 5])

In [5]:
np.expand_dims(l,axis=0)

array([[1, 6, 8, 4, 9, 7, 0, 2, 3, 5]])